php:
  build: ./php
  volumes:
    - ./www:/var/www/html
  ports:
    - "80:80"
  links:
    - "db:mariadb"
  #external_links:
  #  - "mariadb_db_1:mariadb"

db:
  image: mariadb
  #volumes:
  #  - ./mariadb/datadir:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123456
